title: Ivan Hephaestus
description: > # this means to ignore newlines until "baseurl:"
  Just a webpage for different kind of crap
permalink: ':title/'
baseurl: "/ivanhephaestus.github.io" # the subpath of your site, e.g. /blog
url: "https://github.com/IvanHephaestus/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: IvanHephaestus
author-img: david-freeman.jpg # add your photo
about-author: static void __init init(const char *args, ...)
social-github: ivanhephaestus 
social-email: gefestroyale@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
